config/routes.rb
Rails.application.routes.draw do

  resources :customers
  devise_for :users
  
  resources :jobs do
    resources :customers
    resources :tasks
  end
  
    resources :tasks do
      resources :notes
    end
    resources :jobs do
      resources :notes
      
    end
 
    #This needs to be here, otherwise error (as notes resource didn't exist on its own)
    resources :notes
 

    resources :users do
      resources :jobs
    end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 
  authenticated :user do
    root :to => "jobs#index"
  end
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
 
  # Only need optional: true on the belongs_to side of the association, not the has_many side. 
  belongs_to :customer, optional: true
  #accepts_nested_attributes_for :customer
  #attr_accessor :customer_id
  
  has_many :notes, as: :noteable
  has_many :tasks
  belongs_to :user
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

# Before filter - check if user authenticated. If not, redirect to log in page.
before_action :authenticate_user!

  # GET /jobs
  # GET /jobs.json
  def index
    # we aren't building an API, so no need to have users/4/jobs work at all! 
    # if admin == true @jobs - Job.all 
    # else 
    #@user = current_user
    #@jobs = @user.jobs
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    
    
    
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    # Grab the current user ID and populate the @job.user_id
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save  
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :body, :customer_id )
      #params.require(:customer).permit(:customer_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :job_body, size: "120x30" %>
  </div>
  

  <div class="field" >
    <%= form.label :customer %>
    <%= form.collection_select :customer_id, Customer.all, :id, :name, {:prompt => '-- Select a Customer --'} %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_new_note.html.erb
<h3>Add a Note</h3>
<%= form_with(model: note, :remote => true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form_control">
    <!-- ><%= form.label :body %> --> 
    <%= form.text_area :body, id: :note_body, size: "60x10" %>
  </div>
<!-- 
  <div class="field">
    <%= form.label :noteable_type %>
    <%= form.text_field :noteable_type, id: :note_noteable_type %>
  </div>

  <div class="field">
    <%= form.label :noteable_id %>
    <%= form.number_field :noteable_id, id: :note_noteable_id %>
  </div>
 --> 
    <%= form.hidden_field :noteable_type, id: :note_noteable_type %>
    <%= form.hidden_field :noteable_id, id: :note_noteable_id %>


  <div class="actions">
    <%= form.submit %>

	

	
  </div>
<% end %>

app/views/jobs/_new_task.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title %>
  </div>
  
  <%= form.label :job_id %>
   <%= form.text_field :job_id %>
   
   <%#= form.hidden_field :job_id, :value => @job.id %>
   
    <%#= form.hidden_field :job_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<div style="width: 100%; height: 50px; background-color: #a9a9a9; color: #000;"><%= link_to 'New Job +', new_job_path %></div>
<h1>All Jobs</h1>

<table class="table">
  <thead>
    <tr>
	<th scope="col">Job ID</th>
      <th scope="col">Title</th>
	  <th scope="col">Submitted</th>
	  <th scope="col">Updated</th>
	  <th scope="col">Time PH</th>
      <!-- <th>Body</th> --> 
	   <th scope="col">DEV: User ID</th>
	    <th scope="col">DEV: Customer ID</th>
	     <th scope="col">Assigned To (Designer)</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.id, job %></td>
		
		<td><strong><%= link_to job.title, job %></strong></td>
		<td><%= time_ago_in_words(job.created_at) %></td>
		<td><%= time_ago_in_words(job.updated_at) %></td>
		<td><%=Time.use_zone('Sydney') { Time.current }.strftime("%I:%M %p") %></td>
        <!-- <td><%= job.body %></td> --> 
		 <td><%= job.user_id %></td>
		  <td><%= job.customer_id %></td>
		 <td><%= link_to job.user.email, job.user %></td>
        <td><%= link_to 'show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<div class="row"><!-- still neeed to end this div -->
<div class="border col-md-6 " >

<p id="notice"><%= notice %></p>

<h1><%= @job.title %></h1>
<hr/>
<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>
<hr/>


<table class="table">
  <thead>
	  <tr>
		<td>Submitted: <strong><%= time_ago_in_words(@job.created_at) %> ago </strong> </td>
    </tr>
	  <tr>
		<td>Updated: <strong><%= time_ago_in_words(@job.updated_at) %> ago </strong></td>
    </tr>
  </thead>
</table>


	<div style="border: 1px dashed #a9a9a9;">
	JOB CUSTOMER ID
		<h1><%= @job.customer_id %> </h1>
	</div>
	
	<div style="border: 1px dashed #a9a9a9;">
	JOB ID
		<h1><%= @job.to_param %> </h1>
	</div>
	
  <%= params.inspect %>




	<strong>Job User Id:</strong> 
	<%#= @job.user.id %>


<h3>Creative Brief</h3>
<p>
<%= simple_format @job.body %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>


</div><!-- col-md-8-->

<div class="border col-md-6">


<h3>Notes On This job </h3>

<table class="table">
  <thead>
  
	<% @job.notes.each do |note| %>
	  <tr>
		<td><%= note.body %></td>
		<td><%= time_ago_in_words(note.created_at) %> ago</td>
		<td><%= note.created_at.strftime('%m/%d/%Y') %></td>
		<td><%= link_to "edit", edit_note_path(note) %></td>
		<% end %>
    </tr>
  </thead>
</table>

	<%#= render :partial=>"new_seat", :locals=>{:seat=>Seat.new(:flight_id=>@flight.id)} %>
	<%#= render :partial=>"new_note", :locals=>{:note=>Note.new(:noteable_type=>"job", :noteable_id=>3 )} %>

<!-- https://resources.oreilly.com/examples/9780596515775/blob/master/code/chap7_hfror_code_20081129/app/views/flights/show.html.erb -->
	
	<!-- The thing to remember with AJAX is that you don't redirect the request (normally), you just generate some text to send back to the browser. -->



	<!-- Use build here, due to the polymorphic association --> 
<%= render :partial=>"new_note", :locals=>{:note=>@job.notes.build} %>





<!-- 
	<hr/>
	<h3>Add a Task</h3>
	<ul>
		<% @job.tasks.each do |task| %>
		<li><%= task.created_at.strftime('%m/%d/%Y') %> - 
			<%= task.title %> - <%= link_to "edit", edit_task_path(task) %>
			<% end %></li>
		</ul>

		<%#= render :partial=>"new_seat", :locals=>{:seat=>Seat.new(:flight_id=>@flight.id)} %>
		<%#= render :partial=>"new_note", :locals=>{:note=>Note.new(:noteable_type=>"job", :noteable_id=>3 )} %>

		<!-- Use Task.new here, due to the has_many association (I think) --> 
	
	<%#= render :partial=>"new_task", :locals=>{:task=>Task.new(:job_id=>@job.id)} %>

	</div><!-- col-md-4-->